name: 03 - Workflow Runners
on: 
    workflow_dispatch:
    push:
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
          - name: Show OS
            run: |
                echo "This job is running on an Ubuntu runner."
                echo "Runner OS: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
          - name: Show OS
            shell: bash
            run: |
<<<<<<< HEAD
                echo "This job is running on a Windows runner."
                echo "Runner OS $RUNNER_OS"
=======
                echo: "This job is running on a Windows runner."
                echo: "Runner OS: $RUNNER_OS"
>>>>>>> 9674ac03e9847bc28080ff913e570dd1bd42007a
    mac-echo:
        runs-on: macos-latest
        steps:
          - name: Show OS
            run: |
                echo "This job is running on a MacOS runner."
                echo "Runner OS: $RUNNER_OS"
